server:
  port: 7010

spring:
  application:
    name: erp-auth-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
      config:
        server-addr: http://localhost:8848
        file-extension: yaml
feign:
  sentinel:
    enabled: true


jwt:
  secret: ZBvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByYZ
  expiration-time: 12000