server:
  port: 7010

spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
      config:
        server-addr: http://localhost:8848
  redis:
    host: localhost
    database: 1