server:
  port: 7000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
      config:
        server-addr: http://localhost:8848
        file-extension: yaml
        shared-configs[0]:
          data-id: common.yaml
          refresh: true
  redis:
    host: localhost
    port: 6379
    password:
    database: 0

safety:
  ignore:
    urls:
      - /jobs
      - /articles

jwt:
  secret: ZBvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByYZ