server:
  port: 7000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
      config:
        server-addr: http://localhost:8848
  redis:
    host: localhost
    port: 6379
    password:
    database: 0