server:
  port: 7000

spring:
  application:
    name: erp-gateway-service
  profiles:
    active: @profiles.active@
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # 使用小写service-id
    nacos:
      discovery:
        server-addr: http://localhost:8848
      config:
        server-addr: http://localhost:8848
        file-extension: yaml
        group: GATEWAY_GROUP
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  sleuth:
    sampler:
      probability: 1

safety:
  ignore:
    urls:
      - /jobs
      - /articles

jwt:
  secret: ZBvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByYZ

router:
  open-apis:
    - /auth/register
    - /auth/login
  dispensable-apis:
    - /jobs

# 开启SpringBoot-Admin的监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always