server:
  port: 7000

spring:
  application:
    name: erp-gateway-service
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # 使用小写service-id
    nacos:
      discovery:
        server-addr: http://localhost:8848
      config:
        server-addr: http://localhost:8848
        file-extension: yaml
  redis:
    host: localhost
    port: 6379
    password:
    database: 0

safety:
  ignore:
    urls:
      - /jobs
      - /articles
jwt:
  secret: ZBvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByYZ

# 开启SpringBoot-Admin的监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always