version: '3'
services:
  nacos:
    image: nacos/nacos-server:2.0.3-slim
#    build:
#      context: ./nacos
    container_name: nacos
    env_file:
      - ./env/nacos-mysql.env
    volumes:
      - ./logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    restart: always