server:
  port: 7020
  servlet:
    context-path: /user

spring:
  application:
    name: erp-user-service
  profiles:
    active: dev
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted_time
      logic-delete-value: UNIX_TIMESTAMP()
      logic-not-delete-value: 0