server:
  port: 7020
  servlet:
    context-path: /user

spring:
  application:
    name: erp-user-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
      config:
        server-addr: http://localhost:8848
        file-extension: yaml