server:
  port: 7020
  servlet:
    context-path: /user

spring:
  application:
    name: erp-user-service
  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted_time
      logic-delete-value: UNIX_TIMESTAMP()
      logic-not-delete-value: 0

logging:
  config: classpath:log4j2.xml