server:
  port: 7020

spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
      config:
        server-addr: http://localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8849
  datasource:
    name: geebox
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/spring_erp?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: admin
    password: admin@123
  redis:
    host: localhost
    port: 6379
    password:
    database: 0